
wget https://www.piwheels.org/simple/pyserial/pyserial-3.5-py2.py3-none-any.whl
wget https://www.piwheels.org/simple/rpi-gpio/RPi.GPIO-0.7.1-cp311-cp311-linux_armv7l.whl
wget https://www.piwheels.org/simple/python-vlc/python_vlc-3.0.20123-py3-none-any.whl
wget https://www.piwheels.org/simple/xlrd3/xlrd3-1.1.0-py2.py3-none-any.whl
wget https://www.piwheels.org/simple/striprtf/striprtf-0.0.26-py3-none-any.whl
wget https://www.piwheels.org/simple/pyrtitions/pyrtitions-0.2.3-py3-none-any.whl
wget https://www.piwheels.org/simple/unidecode/Unidecode-1.3.8-py3-none-any.whl
wget https://www.piwheels.org/simple/ebooklib/EbookLib-0.18-py3-none-any.whl
wget https://www.piwheels.org/simple/bs4/bs4-0.0.2-py2.py3-none-any.whl
wget https://www.piwheels.org/simple/mutagen/mutagen-1.47.0-py3-none-any.whl
wget https://www.piwheels.org/simple/mido/mido-1.3.2-py3-none-any.whl
wget https://www.piwheels.org/simple/requests/requests-2.31.0-py3-none-any.whl
wget https://www.piwheels.org/simple/pbkdf2/pbkdf2-1.3-py3-none-any.whl
wget https://www.piwheels.org/simple/requests-oauthlib/requests_oauthlib-2.0.0-py2.py3-none-any.whl
wget https://www.piwheels.org/simple/cryptography/cryptography-42.0.7-cp311-cp311-linux_armv7l.whl
wget https://www.piwheels.org/simple/py-machineid/py_machineid-0.5.1-py3-none-any.whl
wget https://www.piwheels.org/simple/wikipedia/wikipedia-1.4.0-py3-none-any.whl
wget https://www.piwheels.org/simple/dbus-python/dbus_python-1.3.2-cp311-cp311-linux_armv7l.whl
wget https://www.piwheels.org/simple/sdbus-networkmanager/sdbus_networkmanager-2.0.0-py3-none-any.whl
wget https://www.piwheels.org/simple/sdbus/sdbus-0.11.1-cp311-cp311-linux_armv7l.whl
wget https://www.piwheels.org/simple/beautifulsoup4/beautifulsoup4-4.12.3-py3-none-any.whl
wget https://www.piwheels.org/simple/cffi/cffi-1.16.0-cp311-cp311-linux_armv7l.whl
wget https://www.piwheels.org/simple/lxml/lxml-5.2.2-cp311-cp311-linux_armv7l.whl
wget https://www.piwheels.org/simple/six/six-1.16.0-py2.py3-none-any.whl
wget https://www.piwheels.org/simple/packaging/packaging-23.2-py3-none-any.whl
wget https://www.piwheels.org/simple/charset-normalizer/charset_normalizer-3.3.2-py3-none-any.whl
wget https://www.piwheels.org/simple/idna/idna-3.7-py3-none-any.whl
wget https://www.piwheels.org/simple/urllib3/urllib3-2.2.1-py3-none-any.whl
wget https://www.piwheels.org/simple/certifi/certifi-2024.2.2-py3-none-any.whl
wget https://www.piwheels.org/simple/oauthlib/oauthlib-3.2.2-py3-none-any.whl
wget https://www.piwheels.org/simple/pycparser/pycparser-2.22-py3-none-any.whl
wget https://www.piwheels.org/simple/soupsieve/soupsieve-2.5-py3-none-any.whl
wget https://www.piwheels.org/simple/build/build-1.2.1-py3-none-any.whl

