"""
 bnote project
 Author : Eurobraille
 Date : 2024-07-16
 Licence : Ce fichier est libre de droit. Vous pouvez le modifier et le redistribuer à votre guise.
"""

# Messages that can be received from STM32 and send to STM32.
KEY_DEVICE_LANGUAGE = b'l'
KEY_KEYBOARD_LANGUAGE = b'g'
KEY_USB_HID_MODE = b'h'
KEY_BRAILLE_KEYBOARD_MODE = b'u'
KEY_BRAILLE_KEYBOARD_B78 = b'a'
KEY_COMMAND_INVERTED_MODE = b'k'
KEY_INTERACTIVE_KEYS_MODE = b'i'
KEY_DEVICE_DATE_AND_TIME = b't'
KEY_BATTERY = b'b'
KEY_USB_SIMUL_ESYS = b'e'
KEY_STANDBY = b'm'

VALUE_LIGHT_PRESS = b'L'
VALUE_STRONG_PRESS = b'M'
VALUE_CONSECUTIVE_PRESS = b'D'
VALUE_DOUBLE_LIGHT_PRESS = b'l'
VALUE_DOUBLE_STRONG_PRESS = b'm'

VALUE_BATTERY_PERCENT = b'P'
VALUE_BATTERY_INTENSITY = b'A'
VALUE_BATTERY_VOLTAGE = b'V'
VALUE_BATTERY_STATE = b'E'

VALUE_STANDBY_TRANSPORT = b'T'
VALUE_STANDBY_SHUTDOWN = b'S'

# Messages that can be sent to STM32.
KEY_CHARACTERISTICS = b'C'
KEY_RESET_PARAMETERS = b'r'
KEY_DISPLAY_STATICS_DOTS = b'D'
KEY_DISPLAY_BLINKINGS_DOTS = b'd'
KEY_DEBUG_TEXT = b'T'
KEY_SPEECH_DONE = b'v'
KEY_INTERNAL_EXIT = b'X'
KEY_ASK_SHUTDOWN_OR_TRANSPORT = b's'

# Messages that can be received from STM32.
KEY_FIRMWARE_VERSION = b'R'
KEY_DEVICE_SUB_TYPE = b'y'
KEY_DEVICE_LENGTH = b'L'
KEY_SERIAL_NUMBER = b'S'
KEY_OPTIONS = b'O'
KEY_DEVICE_NAME = b'N'
KEY_INTERNAL_FUNCTION_ENTER = b'P'
KEY_INTERNAL_FUNCTION_EXIT = b'p'
KEY_BLUETOOTH_FUNCTION_ENTER = b'Z'
KEY_BLUETOOTH_FUNCTION_EXIT = b'z'
KEY_BRAILLE_KEYS = b'B'
KEY_COMMAND_KEYS = b'c'
KEY_INTERACTIVE_KEYS = b'I'
KEY_SHUTDOWN_PI = b's'
KEY_SPEECH = b'V'
KEY_APP_NAME = b'n'
